import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from 'typescript';
const scratch=resolve('.sites-runtime/registration-tests');mkdirSync(scratch,{recursive:true});
const compile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
writeFileSync(resolve(scratch,'schema.mjs'),compile(readFileSync('lib/registration-schema.ts','utf8')));
writeFileSync(resolve(scratch,'db.mjs'),'export function getRegistrationDb(){if(!globalThis.__testDb)throw new Error("storage unavailable");return globalThis.__testDb}');
writeFileSync(resolve(scratch,'route.mjs'),compile(readFileSync('app/api/register/route.ts','utf8')).replaceAll('"@/db"','"./db.mjs"').replaceAll('"@/lib/registration-schema"','"./schema.mjs"'));
const {POST,GET}=await import(pathToFileURL(resolve(scratch,'route.mjs')).href);
const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('drizzle/0000_furry_inhumans.sql','utf8'));
const binding={prepare(query){let values=[];return {bind(...args){values=args;return this},async first(){return sql.prepare(query).get(...values)??null},async run(){const r=sql.prepare(query).run(...values);return {success:true,meta:r}}}}};
globalThis.__testDb=binding;
const origin='https://shimane-ai-hackathon-2026.takemasa.chatgpt.site';
const student={kind:'student',name:'検証用 学生',email:'TEST@example.invalid',school:'検証用学校',schoolType:'高校',grade:'2年',experience:'はじめて・ほぼ未経験',ageGroup:'minor',guardianConsent:true,areas:['教育'],message:'検証用データ',consent:true,updatesOptIn:false};
const company={kind:'business',name:'検証用 担当者',email:'partner@example.invalid',organization:'検証用企業',department:'企画',location:'島根県松江市',participation:'interest',interests:['まずは話を聞きたい','課題の提供'],areas:['企業の業務改善'],message:"'; DROP TABLE student_applications; --",consent:true,updatesOptIn:true};
const send=(data,opts={})=>POST(new Request(`${origin}/api/register`,{method:'POST',headers:{'content-type':'application/json',origin,...opts.headers},body:JSON.stringify({data,requestId:opts.requestId??crypto.randomUUID(),startedAt:Date.now()-3000,website:'',...opts.envelope})}));
test('student persists, normalizes email, saves guardian and consent, and exposes only receipt',async()=>{const r=await send(student);assert.equal(r.status,201);const output=await r.json();assert.deepEqual(Object.keys(output),['receipt']);const row=sql.prepare('SELECT * FROM student_applications').get();assert.equal(row.email,'test@example.invalid');assert.equal(row.guardian_consent,1);assert.equal(row.updates_opt_in,0);assert.equal(row.consent_version,'2026-09-13-v1')});
test('business interest, participation and opt-in persist safely with parameterized SQL',async()=>{const r=await send(company);assert.equal(r.status,201);const row=sql.prepare('SELECT * FROM business_registrations').get();assert.equal(row.participation,'interest');assert.equal(row.updates_opt_in,1);assert.equal(row.message,company.message);assert.deepEqual(JSON.parse(row.interests),company.interests);assert.equal(sql.prepare('SELECT COUNT(*) as n FROM student_applications').get().n,1)});
test('same request ID is idempotent, including simultaneous attempts',async()=>{const requestId=crypto.randomUUID();const first=await send(student,{requestId});const receipt=(await first.json()).receipt;const before=sql.prepare('SELECT COUNT(*) as n FROM student_applications').get().n;const second=await send(student,{requestId});assert.equal((await second.json()).receipt,receipt);assert.equal(sql.prepare('SELECT COUNT(*) as n FROM student_applications').get().n,before);const concurrentId=crypto.randomUUID();const outputs=await Promise.all([send(company,{requestId:concurrentId}),send(company,{requestId:concurrentId})]);assert.equal((await outputs[0].json()).receipt,(await outputs[1].json()).receipt);assert.equal(sql.prepare('SELECT COUNT(*) as n FROM business_registrations WHERE request_id=?').get(concurrentId).n,1)});
test('invalid consent, invalid email, no guardian permission, blank name and missing company interest are rejected',async()=>{for(const data of [{...student,consent:false},{...student,email:'bad'},{...student,guardianConsent:false},{...student,name:' '},{...company,interests:[]}])assert.equal((await send(data)).status,400)});
test('cross-site requests, honeypot and oversize bodies are rejected',async()=>{assert.equal((await send(student,{headers:{origin:'https://bad.example'}})).status,403);assert.equal((await send(student,{envelope:{website:'spam'}})).status,400);assert.equal((await send(student,{envelope:{startedAt:Date.now()+1000}})).status,400);assert.equal((await send({...student,message:'a'.repeat(18000)})).status,413)});
test('GET never exposes applications',async()=>{const response=GET();assert.equal(response.status,405);assert.ok(!(await response.text()).includes('example.invalid'))});
test('storage failure returns recoverable 503 without fake success',async()=>{globalThis.__testDb=null;const r=await send(student);assert.equal(r.status,503);assert.equal((await r.json()).receipt,undefined);globalThis.__testDb=binding});
test('rate-limiting works and stores no raw visitor IP',async()=>{let last;for(let i=0;i<41;i++)last=await send(company,{headers:{'cf-connecting-ip':'192.0.2.20'}});assert.equal(last.status,429);const rows=sql.prepare('SELECT key FROM submission_limits').all();assert.ok(rows.every(r=>/^[a-f0-9]{64}$/.test(r.key)));});
after(()=>{sql.close();delete globalThis.__testDb;rmSync(scratch,{recursive:true,force:true})});
