import { ArrowDown, ArrowUpRight, ArrowRight, Sparkles, CalendarDays, MapPin, Users, Trophy, GraduationCap, Building2, Sprout, Bus, Landmark, HeartHandshake, Compass, BookOpen, Code2, Lightbulb, Presentation, Check } from "lucide-react";
import { RegistrationSection, FAQ } from "./registration";
const themes=[{Icon:Compass,label:"観光"},{Icon:BookOpen,label:"教育"},{Icon:HeartHandshake,label:"福祉"},{Icon:Sprout,label:"農業・林業"},{Icon:Bus,label:"交通"},{Icon:Landmark,label:"地域文化"}];
const steps=[
{title:"地域を知る。仲間と出会う。",text:"島根や企業の課題を知るところからスタート。AIの使い方を学び、チームで挑戦するテーマを見つけます。",Icon:Users,tag:"発見・チームづくり"},
{title:"「あったらいいな」を描く。",text:"誰の、どんな困りごとを変えたい？ 現場の声と自分たちの視点を重ねて、アイデアを育てます。",Icon:Lightbulb,tag:"アイデアづくり"},
{title:"AIと一緒に、つくってみる。",text:"メンターのサポートを受けながら、アイデアを実際に触れる試作品へ。まず動かす、その一歩を。",Icon:Code2,tag:"プロトタイプ制作"},
{title:"届ける。その先につながる。",text:"つくったものを発表し、企業・金融・行政関係者などからのフィードバックを、次の挑戦につなげます。",Icon:Presentation,tag:"成果発表・審査"}];
export default function Home(){return <>
<a className="skip-link" href="#main">本文へ移動</a>
<header className="site-header"><a className="brand" href="#" aria-label="島根AI ハッカソン トップ"><img className="brand-mark" src="/brand/logo-symbol-navy-transparent.png" alt="" width={683} height={678}/><img className="brand-wordmark" src="/brand/logo-wordmark-navy-transparent.png" alt="ShimaneAI 島根AI" width={920} height={205}/></a><nav aria-label="メインナビゲーション"><a href="#about">ハッカソンとは</a><a href="#outline">開催概要</a><a href="#co-creation">地域との連携</a><a href="#partners">企業の皆さまへ</a><a href="#faq">よくある質問</a></nav><a className="button button-small button-navy" href="#entry-student">参加を申し込む <ArrowUpRight size={17}/></a></header>
<main id="main">
<section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><Sparkles size={16}/> SHIMANE AI HACKATHON 2027</p><p className="hero-intro">学生の発想と、地域の力と、AI。</p><h1 id="hero-title">この地から、<br/>まだ見ぬ<span className="future-word">未来</span>を。</h1><p className="hero-description">島根の仕事や暮らしに、新しい可能性を。<br/>仲間と学び、考え、AIでかたちにするハッカソン。</p><p className="hero-date">2027<span>年</span> 2月末 — 3月上旬 <small>開催予定</small></p><div className="hero-actions"><a className="button button-yellow" href="#entry-student">学生として参加する <ArrowUpRight size={20}/></a><a className="hero-business" href="#entry-business">企業・団体として関わる <ArrowRight size={18}/></a></div><p className="hero-note"><Check size={16}/> 初心者歓迎 <span/> プログラミング経験不問</p></div><div className="hero-visual"><img className="hero-image" src="/hero.webp" alt="青い水辺と緑を背景に、パソコンを囲んでアイデアを交わす学生たちのイメージ" width={1536} height={1024} fetchPriority="high"/><div className="image-shade"/><span className="hero-image-label">SHIMANE × AI × OUR FUTURE</span><div className="prize"><Trophy size={21}/><span>優勝賞金〈予定〉</span><strong>10<span>万円</span></strong></div><div className="visual-caption"><span>人と、自然と、テクノロジーと。</span><strong>人と地域の可能性を、AIでひらく。</strong></div><span className="image-credit">イメージビジュアル</span></div></section>
<div className="event-bar"><div className="event-name">島根AIハッカソン<span>2027</span></div><div className="event-fact"><CalendarDays/><span><strong>2月末〜3月上旬</strong><small>2027年・開催予定</small></span></div><div className="event-fact"><MapPin/><span><strong>島根県松江市</strong><small>会場調整中</small></span></div><div className="event-free">学生参加費 <strong>無料</strong></div><a href="#about" aria-label="ハッカソンについて読む"><ArrowDown size={22}/></a></div>
<section className="section about-section" id="about"><div className="section-kicker">01 — ABOUT</div><div className="about-grid"><h2>「あったらいいな」を、<br/><span className="teal">AIで、動くかたちに。</span></h2><div><p className="lead">島根の未来をつくるのは、<br/>ここにある課題に、可能性を見つける力。</p><p>ハッカソンは、仲間とアイデアを出し合い、短い期間で試作品をつくるイベントです。今回は、島根県の学生たちがAIの力を使って、地域や企業の課題解決に挑むハッカソンを企画しています。</p><p>過疎地域の可能性を、もっと大きく。地域にある知恵や経験にAIの力を重ねて、仕事や暮らしの「こうなったらいいな」を、自分たちの手でかたちにしませんか。</p></div></div><div className="feature-grid"><article><span className="feature-number">01</span><Sparkles className="feature-icon"/><h3>はじめてでも、つくれる。</h3><p>プログラミングの経験は問いません。AIメンターが伴走し、最初の一歩からサポートします。</p></article><article><span className="feature-number">02</span><Users className="feature-icon"/><h3>ひとりの気づきが、チームの力に。</h3><p>学校や得意分野を越えて出会う仲間と一緒に。技術も、発想も、地域への思いも、大切な力です。</p></article><article><span className="feature-number">03</span><ArrowUpRight className="feature-icon"/><h3>その挑戦が、地域につながる。</h3><p>成果発表で企業や地域の人にアイデアを届けます。一日の出会いを、その先の連携のきっかけに。</p></article></div></section>
<section className="theme-section"><div className="section-inner"><div className="theme-heading"><p className="section-kicker">OUR CHALLENGE</p><h2>島根の日常に、<br className="mobile-break"/>新しい選択肢を。</h2><p>テーマは「AIの力で島根県の課題を解決せよ」。<br/>身近な気づきから、挑戦が始まります。</p></div><div className="theme-list">{themes.map(({Icon,label})=><div key={label}><Icon size={26}/><span>{label}</span></div>)}</div><p className="theme-examples">たとえば、地域の魅力を届ける観光案内。学びを支える仕組み。農林業の仕事を助けるツール。<br/>ここで挙げたものはアイデアの例です。あなたの視点で、島根の可能性を見つけてください。</p></div></section>
<section className="section outline-section" id="outline"><div><p className="section-kicker">02 — EVENT INFORMATION</p><h2>挑戦の舞台は、<br/><span className="teal">松江。</span></h2><p>学生も、企業も、地域も。<br/>一緒に未来を考える一日を。</p><a className="text-link" href="https://enun.jp/" target="_blank" rel="noopener noreferrer">会場候補 ENUN 公式サイト <ArrowUpRight size={17}/></a></div><dl className="outline-table"><div><dt>開催時期</dt><dd><strong>2027年2月末〜3月上旬（予定）</strong><small>日程・開催時刻は、決まり次第ご案内します。</small></dd></div><div><dt>会場</dt><dd>島根県松江市内（予定）<small>会場候補：ENUN（縁雲）／調整中</small></dd></div><div><dt>対象</dt><dd>島根県内の学生<small>大学生・高校生・高専生・専門学生など</small></dd></div><div><dt>学生定員</dt><dd>約10名（予定）</dd></div><div><dt>参加費</dt><dd><strong className="teal">無料</strong><small>学生参加者</small></dd></div><div><dt>優勝賞金</dt><dd><strong className="prize-text">10万円</strong><small>予定</small></dd></div><div><dt>企画・主催</dt><dd>ShimaneAI（島根AI）</dd></div></dl></section>
<section className="program-section" id="program"><div className="section-inner"><p className="section-kicker">03 — PROGRAM</p><div className="section-heading-row"><h2>アイデアが動き出す、<br className="mobile-break"/>一日の流れ。</h2><p>AIメンターが伴走します。<br/>詳細な時間割は後日ご案内します。</p></div><div className="program-grid">{steps.map(({title,text,Icon,tag},i)=><article key={title}><div className="step-top"><span>STEP 0{i+1}</span><Icon size={25}/></div><p className="step-tag">{tag}</p><h3>{title}</h3><p>{text}</p></article>)}</div><p className="small-note">当日のプログラム・審査員は調整中です。内容が変更になる場合があります。</p></div></section>
<section className="co-creation section" id="co-creation"><div className="collab-heading"><p className="section-kicker">REGIONAL CO-CREATION</p><span className="status-label">連携に向けて調整中</span></div><div className="collab-grid"><div><p className="collab-name">ShimaneAI <span>×</span> TSK「みらチャレ」</p><h2>「やってみたい」が、<br/>地域とつながる。</h2></div><div><p>若者の挑戦を応援する「みらチャレ」との連動を視野に、ハッカソンの企画を進めています。</p><p>地域の人や企業との出会いから課題を見つけ、AIを使ってアイデアを試す。その経験を、学生の次の挑戦と、島根のこれからにつなげていくことを目指します。</p><p className="collab-note">連携内容・実施体制は調整中です。決まり次第、このページでお知らせします。</p><a className="text-link" href="https://mirachalle-shimane.com/" target="_blank" rel="noopener noreferrer">「みらチャレ」公式サイト <ArrowUpRight size={17}/></a></div></div></section>
<section className="partners-section" id="partners"><div className="section-inner"><p className="section-kicker">04 — FOR PARTNERS</p><div className="partners-grid"><div><span className="partner-label">企業・金融・行政・団体の皆さまへ</span><h2>若い発想に、<br/>現場の力を。<br/><span>島根の次の一歩を、<br/>一緒に。</span></h2><p>学生の柔軟な発想とAIに、企業が持つ経験や現場の課題が加わる。その出会いから、地域の仕事や暮らしを変える挑戦を育てていきます。</p><a href="#entry-business" className="button button-yellow">企業・団体として登録する <ArrowUpRight size={20}/></a><small>「まずは話を聞きたい」というご登録も歓迎です。</small></div><div className="partner-options"><article><span>01</span><div><h3>成果発表・交流に参加する</h3><p>学生のアイデアと出会い、対話を通して、これからの連携の可能性を見つける。</p></div><Presentation/></article><article><span>02</span><div><h3>現場の課題を届ける</h3><p>日々の業務や地域で感じている困りごとを、学生たちが挑むテーマの種に。</p></div><Lightbulb/></article><article><span>03</span><div><h3>挑戦を支える・共につくる</h3><p>協賛、メンター協力、技術支援など、できることから学生の挑戦を応援する。</p></div><HeartHandshake/></article><article><span>04</span><div><h3>島根AIの活動とつながる</h3><p>今後のイベントやAI活用、地域との連携に関心のある企業・団体も募集しています。</p></div><Building2/></article></div></div></div></section>
<section className="section faq-section" id="faq"><div><p className="section-kicker">05 — FAQ</p><h2>気になること。</h2><p>参加前の疑問にお答えします。</p></div><FAQ/></section>
<RegistrationSection/><section className="closing"><img className="closing-logo" src="/brand/logo-stacked-navy-transparent.png" alt="ShimaneAI 島根AI" width={920} height={878}/><p>SHIMANE × AI × OUR FUTURE</p><h2>この町の未来に、<br className="mobile-break"/>君のアイデアを。</h2><span>島根の力を、AIでもっと。</span></section></main>
<footer className="site-footer"><a className="brand" href="#" aria-label="ShimaneAI トップ"><img className="brand-mark" src="/brand/logo-symbol-navy-transparent.png" alt="" width={683} height={678}/><img className="brand-wordmark" src="/brand/logo-wordmark-navy-transparent.png" alt="ShimaneAI 島根AI" width={920} height={205}/></a><p>人と、自然と、テクノロジーで、もっと豊かな島根を。</p><div><a href="#privacy">個人情報の取り扱い</a><a href="#co-creation">地域との連携</a><small>© 2027 ShimaneAI</small></div></footer><div className="mobile-cta"><a href="#entry-student"><GraduationCap size={18}/>学生の参加申込</a><a href="#entry-business"><Building2 size={18}/>企業・団体の登録</a></div>
</>}
