"use client";
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { ArrowUpRight, Check, GraduationCap, Building2, LoaderCircle } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { areas, partnerInterests, schoolTypes, experiences, studentSchema, businessSchema } from "@/lib/registration-schema";
type Kind="student"|"business";
type Values={name:string;email:string;school:string;schoolType:string;grade:string;experience:string;organization:string;department:string;location:string;participation:string;message:string;areas:string[];interests:string[];consent:boolean;updatesOptIn:boolean;ageGroup:string;guardianConsent:boolean};
const empty:Values={name:"",email:"",school:"",schoolType:"",grade:"",experience:"",organization:"",department:"",location:"",participation:"",message:"",areas:[],interests:[],consent:false,updatesOptIn:false,ageGroup:"",guardianConsent:false};
const qs=[
["プログラミングができなくても参加できますか？","はい。プログラミング経験は問いません。AIを使ってアイデアをかたちにする過程を、メンターがサポートします。地域のことを知っている、絵や文章が得意、人の話を聞くのが好き。そんな強みも生かせます。"],
["ひとりで申し込んでも大丈夫ですか？","個人でのお申し込みを受け付けています。チーム編成については主催者から後日ご案内します。学校や学年を越えて、新しい仲間と出会う機会にしてください。"],
["高校生や高専生も参加できますか？","島根県内の高校生・高専生・大学生・専門学生などを対象としています。18歳未満の方は、保護者の同意を得てお申し込みください。"],
["参加申込をすれば、参加は確定しますか？","フォームの送信は参加の確定ではありません。学生定員は約10名を予定しています。参加可否と当日の詳細は、主催者から後日ご案内します。"],
["当日の時間や持ち物を教えてください。","開催日は2026年12月19日（土）、会場は松江のENUNです。開始・終了時刻やパソコンなどの持ち物については、決まり次第ご案内します。"],
["企業は当日参加を決めていなくても登録できますか？","はい。「まずは関心登録」を選んでください。課題提供、協賛、技術協力、今後のAI活用や地域連携など、関心のある関わり方をお知らせいただけます。企業・団体の参加方法や条件は、ご希望をもとに個別にご相談します。"]];
export function FAQ(){return <Accordion type="single" collapsible className="faq-list">{qs.map(([q,a],i)=><AccordionItem value={`q${i}`} key={q}><AccordionTrigger><span><span className="faq-q">Q.</span>{q}</span></AccordionTrigger><AccordionContent className="faq-answer">{a}</AccordionContent></AccordionItem>)}</Accordion>}
function Field({label,id,required=true,error,children,full=false}:{label:string;id:string;required?:boolean;error?:string;children:ReactNode;full?:boolean}){return <div className={`field ${full?"full":""}`}><label htmlFor={id}>{label}<span className={required?"required":"optional"}>{required?"必須":"任意"}</span></label>{children}{error&&<p id={`${id}-error`} className="field-error">{error}</p>}</div>}
function CheckLabel({id,checked,onChange,children,className=""}:{id:string;checked:boolean;onChange:(v:boolean)=>void;children:ReactNode;className?:string}){return <label htmlFor={id} className={`check-label ${className}`}><Checkbox id={id} checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>}
function EntryForm({kind}:{kind:Kind}){
const [v,setV]=useState<Values>({...empty});const [errors,setErrors]=useState<Record<string,string>>({});const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [receipt,setReceipt]=useState("");const busy=useRef(false);const requestId=useRef("");const startedAt=useRef(0);const trap=useRef<HTMLInputElement>(null);const formRef=useRef<HTMLFormElement>(null);const successRef=useRef<HTMLDivElement>(null);const failureRef=useRef<HTMLDivElement>(null);
useEffect(()=>{startedAt.current=Date.now();requestId.current=crypto.randomUUID()},[]);
useEffect(()=>{if(receipt)successRef.current?.focus()},[receipt]);
useEffect(()=>{if(error)failureRef.current?.focus()},[error]);
const update=<K extends keyof Values>(key:K,value:Values[K])=>{setV(prev=>({...prev,[key]:value}));setErrors(prev=>({...prev,[key]:""}));setError("")};
const id=(name:string)=>`${kind}-${name}`;
const textField=(key:"name"|"email"|"school"|"grade"|"organization"|"department"|"location",label:string,placeholder:string,required=true,full=false)=><Field key={key} label={label} id={id(key)} required={required} full={full} error={errors[key]}><input id={id(key)} name={key} type={key==="email"?"email":"text"} autoComplete={key==="name"?"name":key==="email"?"email":key==="organization"?"organization":"off"} value={v[key]} onChange={e=>update(key,e.target.value)} placeholder={placeholder} required={required} maxLength={key==="email"?254:key==="name"?80:key==="grade"?30:120} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${id(key)}-error`:undefined}/></Field>;
const selectField=(key:"schoolType"|"experience"|"participation"|"ageGroup",label:string,options:readonly (string|{value:string;label:string})[],full=false)=><Field key={key} label={label} id={id(key)} full={full} error={errors[key]}><Select value={v[key]} onValueChange={value=>update(key,value)}><SelectTrigger className="form-select" id={id(key)} aria-required="true" aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${id(key)}-error`:undefined}><SelectValue placeholder="選択してください"/></SelectTrigger><SelectContent position="popper">{options.map(item=>{const val=typeof item==="string"?item:item.value;return <SelectItem className="select-option" value={val} key={val}>{typeof item==="string"?item:item.label}</SelectItem>})}</SelectContent></Select></Field>;
const toggle=(key:"areas"|"interests",item:string,on:boolean)=>update(key,on?[...v[key],item]:v[key].filter(x=>x!==item));
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy.current)return;setError("");const parsed=(kind==="student"?studentSchema:businessSchema).safeParse({...v,kind});if(!parsed.success){const fields:Record<string,string>={};for(const issue of parsed.error.issues){const key=String(issue.path[0]);if(!fields[key])fields[key]=issue.message}setErrors(fields);setTimeout(()=>{formRef.current?.querySelector<HTMLElement>("[aria-invalid='true']")?.focus()},0);return}busy.current=true;setSaving(true);setErrors({});try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);let response:Response;try{response=await fetch("/api/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:requestId.current,startedAt:startedAt.current,website:trap.current?.value??"",data:parsed.data}),signal:controller.signal})}finally{clearTimeout(timer)}const result=await response.json() as {receipt?:string;error?:string};if(!response.ok||!result.receipt)throw new Error(result.error||"送信できませんでした。時間をおいてもう一度お試しください。");setReceipt(result.receipt)}catch(e){setError(e instanceof Error&&e.name!=="AbortError"?e.message:"通信を確認して、もう一度送信してください。入力内容はこの画面に残っています。")}finally{setSaving(false);busy.current=false}}
if(receipt)return <div className="entry-form"><div className="form-success" ref={successRef} tabIndex={-1} role="status"><div className="success-icon"><Check size={32}/></div><h3>{kind==="student"?"参加申込を受け付けました。":"ご登録ありがとうございます。"}</h3><p>{kind==="student"?"島根で、一緒に未来をつくる一歩を。":"島根の新しい挑戦に、つながってくださりありがとうございます。"}</p><p className="receipt">受付番号<strong>{receipt}</strong></p><p>この受付番号をお控えください。<br/>{kind==="student"?"参加可否・当日の詳細は、主催者から後日ご案内します。":"ご希望に応じて、主催者から後日ご連絡します。"}</p><p className="field-help">この画面で受付完了です。自動返信メールは送信されません。</p></div></div>;
return <form className="entry-form" ref={formRef} onSubmit={submit} noValidate aria-busy={saving}><h3 className="form-title">{kind==="student"?"学生の参加申込":"企業・団体の参加／関心登録"}</h3><p className="form-lead">{kind==="student"?"経験よりも、やってみたい気持ちを。まずはあなたのことを教えてください。":"当日参加から、これからの連携まで。関心のある関わり方をお知らせください。"}<br/><em>「必須」</em>の項目をご入力ください。</p><div className="honeypot" aria-hidden="true"><label htmlFor={id("website")}>この欄は空欄にしてください</label><input id={id("website")} name="website" ref={trap} tabIndex={-1} autoComplete="off"/></div><div className="form-grid">
{kind==="business"&&textField("organization","企業・団体名","例：〇〇株式会社",true,true)}
{textField("name",kind==="student"?"お名前":"ご担当者名","例：島根 太郎")}{textField("email","メールアドレス","例：name@example.com")}
{kind==="student"?<>{textField("school","学校名","例：〇〇大学・〇〇高等学校",true,true)}{selectField("schoolType","学校区分",schoolTypes)}{textField("grade","学年","例：2年")}{selectField("experience","AI・プログラミングの経験",experiences,true)}{selectField("ageGroup","年齢区分",[{value:"adult",label:"18歳以上"},{value:"minor",label:"18歳未満"}],true)}{v.ageGroup==="minor"&&<div className="field full"><CheckLabel id={id("guardianConsent")} checked={v.guardianConsent} onChange={val=>update("guardianConsent",val)}>保護者の同意を得て申し込みます。</CheckLabel>{errors.guardianConsent&&<p className="field-error" role="alert">{errors.guardianConsent}</p>}</div>}</>:<>{textField("department","部署・役職","例：企画部・代表",false)}{textField("location","所在地（市区町村）","例：島根県松江市")}{selectField("participation","参加・登録の希望",[{value:"attend",label:"当日の参加を希望する"},{value:"interest",label:"まずは関心登録・情報交換を希望する"}],true)}<fieldset className="field full" aria-describedby={errors.interests?`${id("interests")}-error`:undefined}><legend className="field-label">関心のある関わり方<span className="required">必須・複数選択可</span></legend><div className="choices">{partnerInterests.map((item,i)=><CheckLabel id={id(`interest-${i}`)} key={item} checked={v.interests.includes(item)} onChange={on=>toggle("interests",item,on)} className="choice-item">{item}</CheckLabel>)}</div>{errors.interests&&<p className="field-error" id={`${id("interests")}-error`} role="alert">{errors.interests}</p>}</fieldset></>}
<fieldset className="field full"><legend className="field-label">関心のあるテーマ<span className="optional">任意・複数選択可</span></legend><div className="choices">{areas.map((item,i)=><CheckLabel id={id(`area-${i}`)} key={item} checked={v.areas.includes(item)} onChange={on=>toggle("areas",item,on)} className="choice-item">{item}</CheckLabel>)}</div></fieldset>
<Field label={kind==="student"?"やってみたいこと・質問など":"課題・ご相談・ご質問など"} id={id("message")} required={false} full error={errors.message}><textarea id={id("message")} name="message" value={v.message} onChange={e=>update("message",e.target.value)} placeholder={kind==="student"?"気になっている地域のこと、挑戦したいアイデアなどを自由にお書きください。":"解決したい困りごとや、ご希望の参加・連携方法などをお書きください。"} maxLength={2000} aria-invalid={!!errors.message}/><span className="field-help">2,000文字以内。機密情報は記載しないでください。</span></Field>
</div><div className="consent-box"><CheckLabel id={id("consent")} checked={v.consent} onChange={val=>update("consent",val)}><a href="#privacy">個人情報の取り扱い</a>に同意します。<span className="required">必須</span></CheckLabel>{errors.consent&&<p className="field-error" role="alert">{errors.consent}</p>}<CheckLabel id={id("updatesOptIn")} checked={v.updatesOptIn} onChange={val=>update("updatesOptIn",val)}>島根AIの今後のイベント・AI活用・地域連携に関する案内を希望します。<span className="optional">任意</span></CheckLabel></div>{error&&<div className="form-error" role="alert" tabIndex={-1} ref={failureRef}>{error}</div>}<button className="button button-yellow form-submit" type="submit" disabled={saving}>{saving?<><LoaderCircle className="animate-spin" size={20}/>送信しています…</>:<>{kind==="student"?"参加申込を送信する":"参加・関心登録を送信する"}<ArrowUpRight size={20}/></>}</button><p className="form-caption">{kind==="student"?"送信時点では参加確定ではありません。参加可否は後日ご案内します。":"ご登録により協賛契約や費用が発生することはありません。"}</p></form>
}
type ModelContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
export function RegistrationSection(){const [kind,setKind]=useState<Kind>("student");useEffect(()=>{const sync=()=>{if(location.hash==="#entry-business")setKind("business");else if(location.hash==="#entry-student")setKind("student")};sync();window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync)},[]);
useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const openTool={name:"open_hackathon_registration",title:"申込フォームを開く",description:"学生または企業・団体の申込フォームを表示します。情報を送信・保存しません。",inputSchema:{type:"object",properties:{kind:{type:"string",enum:["student","business"]}},required:["kind"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const k=(input as {kind?:unknown})?.kind;if(k!=="student"&&k!=="business")throw new Error("kind must be student or business");setKind(k);document.getElementById("entry")?.scrollIntoView();await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {form:k,submitted:false}}};try{void Promise.resolve(context.registerTool(openTool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
return <section className="entry-section" id="entry"><span className="entry-anchor" id="entry-student"/><span className="entry-anchor" id="entry-business"/><div className="section-inner"><div className="entry-heading"><p className="section-kicker">06 — JOIN US</p><h2>次の一歩は、ここから。</h2><p>学生の参加申込、企業・団体の参加と関心登録を受け付けています。</p></div><Tabs value={kind} onValueChange={value=>setKind(value as Kind)} className="entry-tabs"><TabsList className="entry-tabs-list" aria-label="申込区分"><TabsTrigger value="student"><GraduationCap/>学生の参加申込</TabsTrigger><TabsTrigger value="business"><Building2/>企業・団体の登録</TabsTrigger></TabsList><TabsContent value="student" forceMount hidden={kind!=="student"}><EntryForm kind="student"/></TabsContent><TabsContent value="business" forceMount hidden={kind!=="business"}><EntryForm kind="business"/></TabsContent></Tabs><div className="privacy" id="privacy"><h3>個人情報の取り扱い</h3><p>運営：ShimaneAI（島根AI）／担当：武田正文。ご入力いただいた情報は、参加の受付・連絡、イベント運営、登録内容に関するご相談への対応に利用します。今後の活動案内は、案内を希望された方にお送りします。応募情報や企業のご相談内容を、この公開ページに掲載することはありません。</p><p>個人情報を第三者へ販売することはありません。課題や連携内容を外部に共有する必要がある場合は、事前にご相談します。登録内容の訂正・削除、案内の停止は、主催者からの連絡への返信でお申し出いただけます。受付番号を添えて本フォームの質問欄からご連絡いただくこともできます。情報は運営上必要な期間保管し、利用の必要がなくなったものから削除します。</p></div></div></section>}
